const mainUrl = 'http://localhost:8080/'

export const shopUrlMain = mainUrl + 'shop/open/'
export const shopthreeUrl = mainUrl + 'shop/open/findWithLimitThree'
export const shopSizeUrl = mainUrl + 'shop/open/size'
export const getBookUrl = mainUrl + 'shop/open/book/'
export const getBookImage = mainUrl + 'shop/open/material/'
export const getShopMaterialsImage = mainUrl + 'shop/open/shopMaterials/'

export const getCartUrl = mainUrl + 'buy/cart/'
export const changeCartUrl = mainUrl + 'buy/cart/update'

export const getPurchases = mainUrl + 'purchase/'
export const getPurchasesSize = mainUrl + 'purchase/size'
export const getOnePurchases = mainUrl + 'purchase/purchase/'

export const getAllparams = mainUrl + 'shop/open/allParams'
export const getTypes = mainUrl + 'shop/open/types'
export const getGenres = mainUrl + 'shop/open/genres'
export const getAllGenres = mainUrl + 'shop/open/allGenres'
export const getGenre = mainUrl + 'shop/open/genre'
export const getSeries = mainUrl + 'shop/open/series'
export const getOneSeries = mainUrl + 'shop/open/oneSeries'
export const getPublishers = mainUrl + 'shop/open/publishers'
export const getAuthors = mainUrl + 'shop/open/authors'
export const getAuthor = mainUrl + 'shop/open/author'
export const getLimitsPrises = mainUrl + 'shop/open/prises'

export const getBanners = mainUrl + 'banner/open/'

export const getReviews = mainUrl + 'review/open/'
export const getReviewsSize = mainUrl + 'review/open/size'
export const createReviews = mainUrl + 'review/create'
export const changeReviews = mainUrl + 'review/change'
export const deleteReviews = mainUrl + 'review/delete'

export const blogUrlMain = mainUrl + 'blog/'
export const blogFindThreeArticleUrl = mainUrl + 'blog/article/find'
export const blogUrlSize = mainUrl + 'blog/size'
export const openArticle = mainUrl + 'blog/article/'
export const blogUrlMaterial = mainUrl + 'blog/material'

export const createArticle = mainUrl + 'article/createArticle'
export const updateArticleUrl = mainUrl + 'article/update'
export const deleteArticleUrl = mainUrl + 'article/delete/'

export const getComments = mainUrl + 'blog/comments/'
export const createComment = mainUrl + 'comment/create'
export const updateCommentUrl = mainUrl + 'comment/update'
export const deleteCommentUrl = mainUrl + 'comment/delete/'

export const authUrl = mainUrl + 'auth/singIn/login'
export const logoutUser = mainUrl + 'auth/logout/'
export const getUserUrl = mainUrl + 'auth/'
export const refreshTokenUrl = mainUrl + 'auth/singIn/refresh'
export const deleteUser = mainUrl + 'auth/delete'
export const createUrl = mainUrl + 'auth/singIn/registration'
export const getIconUrl = mainUrl + 'auth/singIn/getImage/'
export const updateUser = mainUrl + 'auth/update'