export const shopUrlMain = 'http://localhost:8080/shop/open/'
export const shopSizeUrl = 'http://localhost:8080/shop/open/size'
export const getBookUrl = 'http://localhost:8080/shop/open/book/'

export const getAllparams = 'http://localhost:8080/shop/open/allParams'
export const getTypes = 'http://localhost:8080/shop/open/types'
export const getGenres = 'http://localhost:8080/shop/open/genres'
export const getGenre = 'http://localhost:8080/shop/open/genre'
export const getSeries = 'http://localhost:8080/shop/open/series'
export const getOneSeries = 'http://localhost:8080/shop/open/oneSeries'
export const getPublishers = 'http://localhost:8080/shop/open/publishers'
export const getAuthors = 'http://localhost:8080/shop/open/authors'
export const getAuthor = 'http://localhost:8080/shop/open/author'
export const getLimitsPrises = 'http://localhost:8080/shop/open/prises'

export const blogUrlMain = 'http://localhost:8080/blog/'
export const blogUrlSize = 'http://localhost:8080/blog/size'
export const openArticle = 'http://localhost:8080/blog/article/'
export const blogUrlMaterial = 'http://localhost:8080/blog/material'

export const createArticle = 'http://localhost:8080/article/createArticle'
export const updateArticleUrl = 'http://localhost:8080/article/update'
export const deleteArticleUrl = 'http://localhost:8080/article/delete/'

export const getComments = 'http://localhost:8080/blog/comments/'
export const createComment = 'http://localhost:8080/comment/create'
export const updateCommentUrl = 'http://localhost:8080/comment/update'
export const deleteCommentUrl = 'http://localhost:8080/comment/delete/'

export const authUrl = 'http://localhost:8080/auth/singIn/login'
export const logoutUser = 'http://localhost:8080/auth/logout/'
export const getUserUrl = 'http://localhost:8080/auth/'
export const refreshTokenUrl = 'http://localhost:8080/auth/singIn/refresh'
export const deleteUser = 'http://localhost:8080/auth/delete'
export const createUrl = 'http://localhost:8080/auth/singIn/registration'
export const getIconUrl = 'http://localhost:8080/auth/singIn/getImage/'